### ISSUE TITLE
代码结构性问题

### ISSUE THREAD

**Issue by zenghui9977** [GreenPomelo/Undergraduate#10]
可以给一个代码的结构图吗？

**Comment by UZIhuhuhu** [comment]
好的，我们这周完成。谢谢你的建议。

**Comment by UZIhuhuhu** [comment]
> 可以给一个代码的结构图吗？

你是指 `src` 目录下的文件每个是用来做什么的，还是指整个工作的一个流程呢？

**Comment by zenghui9977** [comment]
> > 可以给一个代码的结构图吗？
> 
> 你是指 `src` 目录下的文件每个是用来做什么的，还是指整个工作的一个流程呢？

`src` 目录下的文件每个是用来做什么的

**Comment by QingYouStudio** [comment]
> > > 可以给一个代码的结构图吗？
> > 
> > 
> > 你是指 `src` 目录下的文件每个是用来做什么的，还是指整个工作的一个流程呢？
> 
> `src` 目录下的文件每个是用来做什么的

已经添加完毕，详细请参考项目的 `README.md`
