### ISSUE TITLE
尝试运行出错

### ISSUE THREAD

**Issue by zhanghonggang** [GreenPomelo/Undergraduate#21]
**Describe the bug**
尝试编译后导入微信小程序
错误提示 未找到 app.json 中的定义的 pages "pages/index" 对应的 JS 文件

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50233099/69728016-9e615b80-115e-11ea-9baf-082cdf5423bb.png)

![image](https://user-images.githubusercontent.com/50233099/69727953-77a32500-115e-11ea-9e32-f175a370780c.png)

**Additional context**
终端文件缺失，望解决

**Comment by GooeyNyan** [comment]
这个说来甚是抱歉，API 相关文件涉及数据安全，
相关文件暂时没有开放的计划。

**Comment by zhanghonggang** [comment]
嗯
