### ISSUE TITLE
添加 demo 账户

### ISSUE THREAD

**Issue by UZIhuhuhu** [GreenPomelo/Undergraduate#5]
因为本项目目录里的 `src/api/*` 其实是被我们 `gitignore` 了，所以 `yarn run dev` 启动项目的时候，是会报错的。
所以我们需要某种方式添加 demo 账号，可以使项目启动。

**Comment by ghost** [comment]
小程序计算排名的方法是怎样的？我同学说他显示的是第0名？

**Comment by ghost** [comment]
我没有找到相关的代码，是被gitignore了吗？

**Comment by UZIhuhuhu** [comment]
> 小程序计算排名的方法是怎样的？我同学说他显示的是第0名？

那你同学是第一名，现在已经改过来了 （当时从 0 开始是当做一个 `feature` 了）

**Comment by UZIhuhuhu** [comment]
> 我没有找到相关的代码，是被gitignore了吗？

在 `src/edu-admin-page/pages/score-inquire.wpy` 里的 281 行

```js
this.rank = rankRes.data.data.rank;
```

改为

```js
this.rank = Number(rankRes.data.data.rank) + 1;
```

**Comment by UZIhuhuhu** [comment]
> 我没有找到相关的代码，是被gitignore了吗？

`gitignore` 的是 后端接口的 `API` ，业务代码都在。

**Comment by GooeyNyan** [comment]
计算排名的逻辑当然是在后端计算的，这里是前端相关的代码，是看不到的哟。
后端业务相关的逻辑因为敏感和安全性就不方便透露了。

**Comment by SoloJiang** [comment]
是否需要通过集中的数据管理去实现这些？我觉得甚至在数据缓存方面也需要有集中的管理。比如我不知道现在 `Storage` 里面已经在代码里存在了哪些？包括所占空间。需要引入另一个 `API` -- `wx.getStorageInfoSync()`

**Comment by UZIhuhuhu** [comment]
本学期可能会在开源版本里写上所有 API 对应的 mock
