### ISSUE TITLE
小程序开发难度如何？

### ISSUE THREAD

**Issue by ghost** [GreenPomelo/Undergraduate#8]
我想在一个项目里移植一下小程序的消费水平曲线那个模块。不知道开发起来难度如何？此外，如何使用小程序调用后端？有没有类似的资源。

**Comment by SoloJiang** [comment]
消费曲线实际上是 后端数据 => 前端 canvas charts => 曲线。小程序的后端服务目前没有对外开放的计划，后面可能会通过 oauth2 认证的方式，给第三方权限去获取经用户同意使用的数据。

**Comment by UZIhuhuhu** [comment]
> 我想在一个项目里移植一下小程序的消费水平曲线那个模块。不知道开发起来难度如何？此外，如何使用小程序调用后端？有没有类似的资源。

图表，曲线这种可视化的东西也有很多开源的前端仓库，小程序 `echarts` 仓库之类的
