### ISSUE TITLE
支付密码明文传输

### ISSUE THREAD

**Issue by Dreamupers** [GreenPomelo/Undergraduate#9]
![image](https://user-images.githubusercontent.com/49057488/56081797-f5225b00-5e43-11e9-9ca4-e5369a8d8a25.png)
支付密码，金额，绑定密码是否都使用了明文传输；
session是否为用户识别码，有过期机制吗。

**Comment by solomon-8** [comment]
session与用户识别码无关，为随机的一个uuid，有过期机制。

支付密码，金额，绑定密码这一块之前没有考虑加密，之后准备加密以后再传输。

**Comment by Dreamupers** [comment]
@Solomon-8 但是这个sessionid自从issue提出以来，到现在一直都可以使用，通过http请求可以get到正确信息。
我比较好奇的是，在请求的信息中，除了这个cookie，没有任何和用户相关的信息，也没有openid，如果不是这个cookie，那后台是如何得知这个用户是谁？sessionid是不是使用了小程序的本地储存，如果删除小程序后，重新绑定，sessionid就会改变了。谢谢！

**Comment by solomon-8** [comment]
> @Solomon-8 但是这个sessionid自从issue提出以来，到现在一直都可以使用，通过http请求可以get到正确信息。
> 我比较好奇的是，在请求的信息中，除了这个cookie，没有任何和用户相关的信息，也没有openid，如果不是这个cookie，那后台是如何得知这个用户是谁？sessionid是不是使用了小程序的本地储存，如果删除小程序后，重新绑定，sessionid就会改变了。谢谢！

这个的作用和cookie的作用大概一个意思，然后超时时间这块因为场景更倾向于即开即用，尽量不要再次登录，所以超时时间略长，后台有更新逻辑。如果删除再次绑定就相当于重新登录了一次，更新这个值是合理的操作。

**Comment by GooeyNyan** [comment]
> ![image](https://user-images.githubusercontent.com/49057488/56081797-f5225b00-5e43-11e9-9ca4-e5369a8d8a25.png)
> 支付密码，金额，绑定密码是否都使用了明文传输；
> session是否为用户识别码，有过期机制吗。

这个不能这么看吧，微信强制都是走 HTTPS 协议的，你的 payload 是被加密过的呀。

**Comment by GooeyNyan** [comment]
> ![image](https://user-images.githubusercontent.com/49057488/56081797-f5225b00-5e43-11e9-9ca4-e5369a8d8a25.png)
> 支付密码，金额，绑定密码是否都使用了明文传输；
> session是否为用户识别码，有过期机制吗。

这个你不能这么看吧，微信强制小程序通信走 HTTPS 协议，payload 在传输的时候都是被加密的。
你在客户端和服务端看肯定是明文的啦。
